version : '3.7'

#networks:
#  apache_network:
#    driver: bridge
#  mariadb_network:
#    external: false

services  :
  mariadb :
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  php_74 :
    build: ../php74
    ports:
      - "9000:80"
    volumes:
      - ../src:/var/www/test
    depends_on:
      - mariadb

  adminer :
    image: adminer
    restart: always
    ports:
      - "9001:8080"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb


